[profile.default]
src = "contracts"
out = "foundry-out"
test = "test/foundry"
cache_path = "foundry-cache"

# Compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM settings
evm_version = "london"

# Remappings for dependencies

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

# Gas reporting
# Testing configuration
[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x1"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing
[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# RPC endpoints
[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
yellow = "${YELLOW_RPC_URL}"
yellow_testnet = "${YELLOW_TESTNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# Etherscan settings
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygon_mumbai = { key = "${POLYGONSCAN_API_KEY}" }
yellow = { key = "${YELLOW_EXPLORER_API_KEY}", url = "https://explorer.yellow.org/api" }
yellow_testnet = { key = "${YELLOW_EXPLORER_API_KEY}", url = "https://testnet-explorer.yellow.org/api" }

# CI profile for faster builds
[profile.ci]
fuzz = { runs = 10 }
invariant = { runs = 5 }
optimizer = true
optimizer_runs = 20000

# Intense profile for comprehensive testing
[profile.intense]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }
optimizer = true
optimizer_runs = 1000000 